on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install ansible    
      - name: Run playbook
        run: ansible-playbook patching_using_builtin_modules.yml  
      - name: Ansible CLI
        uses: tomasnorre/ansible-cli-client@0.0.2
        with:
          # Command to execute
          command: ansible-playbook
