on:
  push:
    branches:
    - main
    - release/*
on:
  pull_request:
    branches:
    - main  
on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
- name: Install Dependencies
  run: apt-get ansible    
- name: run playbook
  run: ansible-playbook patching_using_builtin_modules.yml  
- name: Ansible CLI
  # You may pin to the exact commit or the version.
  # uses: tomasnorre/ansible-cli-client@bd08e0a19b445d0a2bc42877fdd7a2e9d632e8e3
  uses: tomasnorre/ansible-cli-client@0.0.2
  with:
    # Command to execute
    command: # default is ansible-playbook
          
